version: "3.7"
services:
  potrebot:
    container_name: potrebot
#    image: slavkadav/potrebot
    build:
      dockerfile: Dockerfile
    ports:
    - "80:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata: